import {
  LayoutDashboard,
  Users,
  CreditCard,
  BookOpen,
  MessageSquare,
  Calendar,
  GraduationCap,
  Megaphone,
  ShoppingCart,
  DollarSign,
  UserCheck,
  BarChart3,
  Settings,
} from 'lucide-react';
import { MENU_KEYS } from './menuKeys';
import { ROUTER } from './routes';

export interface MenuItem {
  menuId: string;
  menuKey?: string;
  isDevelopment?: boolean;
  menuNm: string;
  menuNmEn: string;
  menuUrl: string;
  orderNo: number;
  upperMenuId: string;
  ico?: React.ComponentType<any>;
  role?: string;
  subMenu: SubMenuItem[];
}

export interface SubMenuItem {
  menuId: string;
  menuKey?: string;
  menuNm: string;
  menuNmEn: string;
  menuUrl: string;
  orderNo: number;
  upperMenuId: string;
  role?: string;
  isDevelopment?: boolean;
}

export const menuList: MenuItem[] = [
  {
    menuId: 'M0000000',
    menuKey: MENU_KEYS.HOME,
    isDevelopment: true,
    menuNm: 'Home',
    menuNmEn: 'Home',
    menuUrl: ROUTER.HOME,
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: LayoutDashboard,
    subMenu: [],
  },
  {
    menuId: 'M0000001',
    menuKey: 'ACCOUNTS_PROFILES',
    menuNm: 'Accounts',
    menuNmEn: 'Accounts',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: Users,
    subMenu: [
      {
        menuId: 'M0000044',
        menuKey: MENU_KEYS.ACCOUNTS.PROFILES,
        menuNm: 'Profiles',
        menuNmEn: 'Profiles',
        menuUrl: ROUTER.FR_PROFILES,
        orderNo: 0,
        upperMenuId: 'M0000001',
        role: 'memberYn',
      },
      {
        menuId: 'M0000003',
        menuKey: MENU_KEYS.ACCOUNTS.GROUPS,
        menuNm: 'Groups',
        menuNmEn: 'Groups',
        menuUrl: ROUTER.FR_GROUPS,
        orderNo: 0,
        upperMenuId: 'M0000001',
        role: 'groupYn',
      },
      {
        menuId: 'M0000043',
        menuKey: MENU_KEYS.ACCOUNTS.TAGS,
        menuNm: 'Tags',
        menuNmEn: 'Tags',
        menuUrl: ROUTER.FR_TAG_SETTING,
        orderNo: 0,
        upperMenuId: 'M0000001',
        role: 'tagYn',
      },
    ],
  },
  {
    menuId: 'M0000005',
    menuKey: MENU_KEYS.MEMBERSHIPS,
    menuNm: 'Memberships',
    menuNmEn: 'Memberships',
    menuUrl: ROUTER.MEMBERSHIP_MANAGEMENT,
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: CreditCard,
    role: 'planYn',
    subMenu: [],
  },
  {
    menuId: 'M0000008',
    menuNm: 'Class',
    menuNmEn: 'Class',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: BookOpen,
    subMenu: [
      {
        menuId: 'M0000009',
        menuKey: MENU_KEYS.CLASS.CLASS_MANAGEMENT,
        menuNm: 'Class Management',
        menuNmEn: 'Class Management',
        menuUrl: ROUTER.CLASS,
        orderNo: 0,
        upperMenuId: 'M0000008',
        role: 'classYn',
      },
      {
        menuId: 'M0000013',
        menuKey: MENU_KEYS.CLASS.ATTENDANCE_HISTORY,
        menuNm: 'Attendance History',
        menuNmEn: 'Attendance History',
        menuUrl: ROUTER.ATTENDANCE_HISTORY,
        orderNo: 0,
        upperMenuId: 'M0000008',
        role: 'attendanceHistoryYn',
      },
      {
        menuId: 'M0000014',
        menuKey: MENU_KEYS.CLASS.BULK_ACTIONS,
        menuNm: 'Bulk Actions',
        menuNmEn: 'Bulk Actions',
        menuUrl: ROUTER.BULK_ACTION,
        orderNo: 0,
        upperMenuId: 'M0000008',
        role: 'attendanceHistoryYn',
      },
      {
        menuId: 'M0000045',
        menuKey: MENU_KEYS.CLASS.SELF_CHECK_IN,
        menuNm: 'Self Check-in',
        menuNmEn: 'Self Check-in',
        menuUrl: ROUTER.ATTENDANCE_SELF_REGISTER,
        orderNo: 0,
        upperMenuId: 'M0000008',
        role: 'attendanceHistoryYn',
      },
    ],
  },
  {
    menuId: 'M0000014',
    menuNm: 'Communications',
    menuNmEn: 'Communications',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: MessageSquare,
    subMenu: [
      {
        menuId: 'M0000020',
        menuKey: MENU_KEYS.COMMUNICATIONS.MESSAGING,
        menuNm: 'Messages',
        menuNmEn: 'Messages',
        menuUrl: ROUTER.MESSAGING,
        orderNo: 0,
        upperMenuId: 'M0000014',
        role: 'mailSendYn',
      },
      {
        menuId: 'M0000021',
        menuKey: MENU_KEYS.COMMUNICATIONS.ANNOUNCEMENTS,
        menuNm: 'Announcements',
        menuNmEn: 'Announcements',
        menuUrl: ROUTER.ANNOUNCEMENTS,
        orderNo: 0,
        upperMenuId: 'M0000014',
        role: 'noticeYn',
      },
      {
        menuId: 'M0000023',
        menuKey: MENU_KEYS.COMMUNICATIONS.COMMUNICATIONS_CONVERSATIONS,
        menuNm: 'Conversations',
        menuNmEn: 'Conversations',
        menuUrl: ROUTER.CONVERSATIONS,
        orderNo: 0,
        upperMenuId: 'M0000014',
        role: 'chatYn',
      },
    ],
  },
  {
    menuId: 'M0000024',
    menuNm: '이벤트',
    menuNmEn: 'Events',
    orderNo: 0,
    upperMenuId: 'TOP',
    subMenu: [
      {
        menuId: 'M0000040',
        menuKey: MENU_KEYS.EVENTS.EVENT_MANAGEMENT,
        menuNm: '이벤트 관리',
        menuNmEn: 'Events Management',
        menuUrl: ROUTER.EVENT,
        orderNo: 0,
        upperMenuId: 'M0000024',
        role: 'eventYn',
      },
      {
        menuId: 'M0000012',
        menuKey: MENU_KEYS.EVENTS.TESTINGS,
        menuNm: '승급 관리',
        menuNmEn: 'Testing',
        menuUrl: ROUTER.TESTING_LIST,
        orderNo: 0,
        upperMenuId: 'M0000024',
        role: 'upgradeYn',
      },
    ],
    ico: Calendar,
    role: 'eventYn',
  },
  {
    menuId: 'M0000025',
    menuNm: '학습센터',
    menuNmEn: 'Learning Center',
    menuUrl: ROUTER.LEARN,
    orderNo: 0,
    upperMenuId: 'TOP',
    subMenu: [
      {
        menuId: 'M0000039',
        menuKey: MENU_KEYS.LEARNING_CENTERS.LEARNING_CENTERS,
        menuNm: '학습 센터 관리',
        menuNmEn: 'Learning Centers',
        menuUrl: ROUTER.LEARN,
        orderNo: 0,
        upperMenuId: 'M0000025',
        role: 'studyCenterYn',
      },
      {
        menuId: 'M0000010',
        menuKey: MENU_KEYS.LEARNING_CENTERS.HOMEWORKS,
        menuNm: '과제 관리',
        menuNmEn: 'Homeworks',
        menuUrl: ROUTER.HOMEWORK,
        orderNo: 0,
        upperMenuId: 'M0000025',
        role: 'homeworkYn',
      },
    ],
    ico: GraduationCap,
    role: 'studyCenterYn',
  },
  {
    menuId: 'M0000042',
    menuNm: '마케팅 툴',
    menuNmEn: 'Marketing Tools',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: Megaphone,
    subMenu: [
      {
        menuId: 'M0000041',
        menuKey: MENU_KEYS.MARKETING_TOOLS.FORMS,
        menuNm: '폼 관리',
        menuNmEn: 'Forms',
        menuUrl: ROUTER.FORM,
        orderNo: 0,
        upperMenuId: 'M0000042',
        role: 'formYn',
      },
      {
        menuId: 'M0000046',
        menuKey: MENU_KEYS.MARKETING_TOOLS.AUTOMATIONS,
        menuNm: 'Automations',
        menuNmEn: 'Automations',
        menuUrl: ROUTER.MARKETING_AUTOMATION,
        orderNo: 0,
        upperMenuId: 'M0000042',
        role: 'automationYn',
      },
    ],
  },
  {
    menuId: 'M0000026',
    menuNm: '이스토어',
    menuNmEn: 'eStore',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: ShoppingCart,
    subMenu: [
      {
        menuId: 'M0000027',
        menuKey: MENU_KEYS.ESTORE.ORDERS,
        menuNm: '주문 관리',
        menuNmEn: 'Orders',
        menuUrl: ROUTER.ECOMMERCE_ORDER,
        orderNo: 0,
        upperMenuId: 'M0000026',
        role: 'orderYn',
      },
      {
        menuId: 'M0000028',
        menuKey: MENU_KEYS.ESTORE.PRODUCTS,
        menuNm: '상품 관리',
        menuNmEn: 'Products',
        menuUrl: ROUTER.PRODUCTS,
        orderNo: 0,
        upperMenuId: 'M0000026',
        role: 'productYn',
      },
    ],
  },
  {
    menuId: 'M0000029',
    menuNm: '결제',
    menuNmEn: 'Payments',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: DollarSign,
    subMenu: [
      {
        menuId: 'M0000030',
        menuKey: MENU_KEYS.PAYMENTS.TRANSACTION_ERRORS,
        menuNm: '결제 에러 이력',
        menuNmEn: 'Transaction Errors',
        menuUrl: ROUTER.PAYMENT_ERROR,
        orderNo: 0,
        upperMenuId: 'M0000029',
        role: 'paymentErrorYn',
      },
      {
        menuId: 'M0000031',
        menuKey: MENU_KEYS.PAYMENTS.TRANSACTIONS,
        menuNm: '결제 현황',
        menuNmEn: 'Transactions',
        menuUrl: ROUTER.TRANSACTIONS,
        orderNo: 0,
        upperMenuId: 'M0000029',
        role: 'paymentHistoryYn',
      },
      {
        menuId: 'M0000032',
        menuKey: MENU_KEYS.PAYMENTS.INVOICES,
        menuNm: '청구서',
        menuNmEn: 'Invoices',
        menuUrl: ROUTER.INVOICE,
        orderNo: 0,
        upperMenuId: 'M0000029',
        role: 'invoiceYn',
      },
      {
        menuId: 'M0000033',
        menuKey: MENU_KEYS.PAYMENTS.AUTOPAYS,
        menuNm: '오토페이 현황',
        menuNmEn: 'Autopays',
        menuUrl: ROUTER.AUTOPAY_HISTORY,
        orderNo: 0,
        upperMenuId: 'M0000029',
        role: 'autoPayYn',
      },
    ],
  },
  {
    menuId: 'M0000051',
    menuNm: '스테프',
    menuNmEn: 'Staff',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: UserCheck,
    subMenu: [
      {
        menuId: 'M0000052',
        menuKey: MENU_KEYS.STAFF.STAFF_MEMBERS,
        menuNm: '스테프 관리',
        menuNmEn: 'Staff Members',
        menuUrl: ROUTER.STAFF_MEMBERS,
        orderNo: 0,
        upperMenuId: 'M0000051',
        role: 'frYn',
      },
      {
        menuId: 'M0000053',
        menuKey: MENU_KEYS.STAFF.CLOCK_IN_AND_OUT,
        menuNm: '출퇴근 관리',
        menuNmEn: 'Clock-In / Out',
        menuUrl: ROUTER.CLOCKINOUT,
        orderNo: 0,
        upperMenuId: 'M0000051',
        role: 'staffYn',
      },
      {
        menuId: 'M0000038',
        menuKey: MENU_KEYS.SETTINGS.STAFF_MANAGEMENT,
        menuNm: 'Log & History',
        menuNmEn: 'Log & History',
        menuUrl: ROUTER.STAFF_MANAGEMENT_LOG,
        orderNo: 0,
        upperMenuId: 'M0000051',
        role: 'staffYn',
      },
    ],
  },
  ...(import.meta.env.VITE_ENV_FILE === 'production'
    ? []
    : [
        {
          menuId: 'M0000054',
          menuNm: 'Reports',
          menuNmEn: 'Reports',
          menuUrl: '-',
          orderNo: 0,
          upperMenuId: 'TOP',
          ico: BarChart3,
          isDevelopment: true,
          subMenu: [
            {
              menuId: 'M0000055',
              menuKey: MENU_KEYS.REPORTS.INSIGHTS,
              menuNm: 'Insights',
              menuNmEn: 'Insights',
              menuUrl: ROUTER.REPORTS_INSIGHTS,
              orderNo: 0,
              upperMenuId: 'M0000054',
              role: 'frYn',
              isDevelopment: true,
            },
            {
              menuId: 'M0000056',
              menuKey: MENU_KEYS.REPORTS.REPORTS,
              menuNm: 'Reports',
              menuNmEn: 'Reports',
              menuUrl: ROUTER.REPORTS_REPORTS,
              orderNo: 0,
              upperMenuId: 'M0000054',
              role: 'frYn',
              isDevelopment: true,
            },
          ],
        },
      ]),
  {
    menuId: 'M0000034',
    menuNm: '설정',
    menuNmEn: 'Settings',
    menuUrl: '-',
    orderNo: 0,
    upperMenuId: 'TOP',
    ico: Settings,
    subMenu: [
      {
        menuId: 'M0000049',
        menuKey: MENU_KEYS.SETTINGS.SCHOOL_SETUP,
        menuNm: 'School Setup',
        menuNmEn: 'School Setup',
        menuUrl: ROUTER.SCHOOL_SETUP,
        orderNo: 0,
        upperMenuId: 'M0000034',
        role: 'frYn',
      },
      {
        menuId: 'M0000046',
        menuKey: MENU_KEYS.SETTINGS.PAYMENTS,
        menuNm: 'Payments',
        menuNmEn: 'Payments',
        menuUrl: ROUTER.SETTINGS_PAYMENTS,
        orderNo: 0,
        upperMenuId: 'M0000034',
        role: 'paymentYn',
      },
      {
        menuId: 'M0000048',
        menuKey: MENU_KEYS.SETTINGS.COMMUNICATION,
        menuNm: 'Communication',
        menuNmEn: 'Communication',
        menuUrl: ROUTER.COMMUNICATION,
        orderNo: 0,
        upperMenuId: 'M0000034',
        role: 'communicationYn',
      },
      {
        menuId: 'M0000047',
        menuKey: MENU_KEYS.SETTINGS.SYSTEM_SECURITY,
        menuNm: '시스템 설정',
        menuNmEn: 'System & Security',
        menuUrl: ROUTER.SYSTEM_SECURITY,
        orderNo: 0,
        upperMenuId: 'M0000034',
        role: 'securityYn',
      },
      {
        menuId: 'M0000050',
        menuKey: MENU_KEYS.SETTINGS.SUBSCRIPTION_BILLINGS,
        menuNm: '구독 및 청구',
        menuNmEn: 'Subscription & Billing',
        menuUrl: ROUTER.SUB_BILLING,
        orderNo: 0,
        upperMenuId: 'M0000034',
        role: 'frYn',
      },
    ],
  },
] as MenuItem[];