export const MENU_KEYS = {
  HOME: 'HOME',
  ACCOUNTS: {
    PROFILES: 'ACCOUNTS.PROFILES',
    GROUPS: 'ACCOUNTS.GROUPS',
    TAGS: 'ACCOUNTS.TAGS',
  },
  MEMBERSHIPS: 'MEMBERSHIPS',
  CLASS: {
    CLASS_MANAGEMENT: 'CLASS.CLASS_MANAGEMENT',
    ATTENDANCE_HISTORY: 'CLASS.ATTENDANCE_HISTORY',
    BULK_ACTIONS: 'CLASS.BULK_ACTIONS',
    SELF_CHECK_IN: 'CLASS.SELF_CHECK_IN',
  },
  COMMUNICATIONS: {
    MESSAGING: 'COMMUNICATIONS.MESSAGING',
    ANNOUNCEMENTS: 'COMMUNICATIONS.ANNOUNCEMENTS',
    COMMUNICATIONS_CONVERSATIONS: 'COMMUNICATIONS.COMMUNICATIONS_CONVERSATIONS',
  },
  EVENTS: {
    EVENT_MANAGEMENT: 'EVENTS.EVENT_MANAGEMENT',
    TESTINGS: 'EVENTS.TESTINGS',
  },
  LEARNING_CENTERS: {
    LEARNING_CENTERS: 'LEARNING_CENTERS.LEARNING_CENTERS',
    HOMEWORKS: 'LEARNING_CENTERS.HOMEWORKS',
  },
  MARKETING_TOOLS: {
    FORMS: 'MARKETING_TOOLS.FORMS',
    AUTOMATIONS: 'MARKETING_TOOLS.AUTOMATIONS',
  },
  ESTORE: {
    ORDERS: 'ESTORE.ORDERS',
    PRODUCTS: 'ESTORE.PRODUCTS',
  },
  PAYMENTS: {
    TRANSACTION_ERRORS: 'PAYMENTS.TRANSACTION_ERRORS',
    TRANSACTIONS: 'PAYMENTS.TRANSACTIONS',
    INVOICES: 'PAYMENTS.INVOICES',
    AUTOPAYS: 'PAYMENTS.AUTOPAYS',
  },
  STAFF: {
    STAFF_MEMBERS: 'STAFF.STAFF_MEMBERS',
    CLOCK_IN_AND_OUT: 'STAFF.CLOCK_IN_AND_OUT',
  },
  REPORTS: {
    INSIGHTS: 'REPORTS.INSIGHTS',
    REPORTS: 'REPORTS.REPORTS',
  },
  SETTINGS: {
    SCHOOL_SETUP: 'SETTINGS.SCHOOL_SETUP',
    PAYMENTS: 'SETTINGS.PAYMENTS',
    COMMUNICATION: 'SETTINGS.COMMUNICATION',
    STAFF_MANAGEMENT: 'SETTINGS.STAFF_MANAGEMENT',
    SYSTEM_SECURITY: 'SETTINGS.SYSTEM_SECURITY',
    SUBSCRIPTION_BILLINGS: 'SETTINGS.SUBSCRIPTION_BILLINGS',
  },
} as const;